In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv("Bengaluru_House_Data.csv")

In [3]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
data.shape

(13320, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
for column in data.columns:
    print(data[column].value_counts())

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64

In [7]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [8]:
data.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [10]:
data['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [11]:
data['size'] = data['size'].fillna('2 BHK')

In [12]:
data['bath'] = data['bath'].fillna(data['bath'].median())

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13320 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13320 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [14]:
data['bhk'] = data['size'].str.split().str.get(0).astype(int)

In [15]:
data.head(20)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00,2
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00,2
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00,4
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00,4
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25,3
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00,6
10,Super built-up Area,18-Feb,Whitefield,3 BHK,NaN,1800,2.0,2.0,70.00,3
11,Plot Area,Ready To Move,Whitefield,4 Bedroom,Prrry M,2785,5.0,3.0,295.00,4
12,Super built-up Area,Ready To Move,7th Phase JP Nagar,2 BHK,Shncyes,1000,2.0,1.0,38.00,2
13,Built-up Area,Ready To Move,Gottigere,2 BHK,NaN,1100,2.0,2.0,40.00,2
14,Plot Area,Ready To Move,Sarjapur,3 Bedroom,Skityer,2250,3.0,2.0,148.00,3
15,Super built-up Area,Ready To Move,Mysore Road,2 BHK,PrntaEn,1175,2.0,2.0,73.50,2
16,Super built-up Area,Ready To Move,Bisuvanahalli,3 BHK,Prityel,1180,3.0,2.0,48.00,3
17,Super built-up Area,Ready To Move,Raja Rajeshwari Nagar,3 BHK,GrrvaGr,1540,3.0,3.0,60.00,3
18,Super built-up Area,Ready To Move,Ramakrishnappa Layout,3 BHK,PeBayle,2770,4.0,2.0,290.00,3
19,Super built-up Area,Ready To Move,Manayata Tech Park,2 BHK,NaN,1100,2.0,2.0,48.00,2

In [16]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2117,), dtype=object)

In [17]:
def convertRange(x):
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    try:
        return float(x)
    except:
        return None

In [18]:
data['total_sqft'] = data['total_sqft'].apply(convertRange)

In [19]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056.0,2.0,1.0,39.07,2
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600.0,5.0,3.0,120.00,4
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440.0,2.0,3.0,62.00,3
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521.0,3.0,1.0,95.00,3
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200.0,2.0,1.0,51.00,2

In [20]:
data['price_per_sqt'] = data['price'] * 100000 / data['total_sqft']

In [21]:
data['price_per_sqt']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqt, Length: 13320, dtype: float64

In [22]:
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqt
count,13274.000000,13320.000000,12711.000000,13320.000000,13320.000000,1.327400e+04
mean,1559.626694,2.688814,1.584376,112.565627,2.802778,7.907501e+03
std,1238.405258,1.338754,0.817263,148.971674,1.294496,1.064296e+05
min,1.000000,1.000000,0.000000,8.000000,1.000000,2.678298e+02
25%,1100.000000,2.000000,1.000000,50.000000,2.000000,4.266865e+03
50%,1276.000000,2.000000,2.000000,72.000000,3.000000,5.434306e+03
75%,1680.000000,3.000000,2.000000,120.000000,3.000000,7.311746e+03
max,52272.000000,40.000000,3.000000,3600.000000,43.000000,1.200000e+07

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   area_type      13320 non-null  object
 1   availability   13320 non-null  object
 2   location       13319 non-null  object
 3   size           13320 non-null  object
 4   society        7818 non-null   object
 5   total_sqft     13274 non-null  float64
 6   bath           13320 non-null  float64
 7   balcony        12711 non-null  float64
 8   price          13320 non-null  float64
 9   bhk            13320 non-null  int64
 10  price_per_sqt  13274 non-null  float64
dtypes: float64(5), int64(1), object(5)
memory usage: 1.1+ MB

In [24]:
data['location'] = data['location'].str.strip()

In [25]:
location_count = data['location'].value_counts()

In [26]:
location_count

location
Whitefield                              541
Sarjapur  Road                          399
Electronic City                         304
Kanakpura Road                          273
Thanisandra                             237
                                       ...
Duddanahalli                              1
Doddanakunte                              1
Jogupalya                                 1
Subhash Nagar                             1
Kengeri Satellite Town KHB Apartment      1
Name: count, Length: 1294, dtype: int64

In [27]:
location_count_less_10  = location_count[location_count<=10]

In [28]:
data['location'] = data['location'].apply(lambda x :'other' if x in location_count_less_10 else x)

In [29]:
data['location'].value_counts()

location
other                        2885
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [30]:
data = data[((data['total_sqft']/data['bhk']) >= 300 )]

In [31]:
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqt
count,12530.000000,12530.000000,12014.000000,12530.000000,12530.000000,12530.000000
mean,1594.564544,2.559537,1.587648,111.382401,2.650838,6303.979357
std,1261.271296,1.077938,0.808842,152.077329,0.976678,4162.237981
min,300.000000,1.000000,0.000000,8.440000,1.000000,267.829813
25%,1116.000000,2.000000,1.000000,49.000000,2.000000,4210.526316
50%,1300.000000,2.000000,2.000000,70.000000,3.000000,5294.117647
75%,1700.000000,3.000000,2.000000,115.000000,3.000000,6916.666667
max,52272.000000,16.000000,3.000000,3600.000000,16.000000,176470.588235

In [32]:
def remove_outliners_sqft(df):
    df_output = pd.DataFrame()

    for key, subdf in df.groupby('location'):
        m = np.mean(subdf['price_per_sqt'])
        st = np.std(subdf['price_per_sqt'])

        gen_df = subdf[
            (subdf['price_per_sqt'] > (m - st)) &
            (subdf['price_per_sqt'] <= (m + st))
        ]

        df_output = pd.concat([df_output, gen_df], ignore_index=True)

    return df_output


data = remove_outliners_sqft(data)
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqt
count,10300.000000,10300.000000,9932.000000,10300.000000,10300.000000,10300.000000
mean,1508.431719,2.471650,1.592932,91.286885,2.574854,5659.090455
std,880.736507,0.979483,0.796935,86.346962,0.897683,2265.883017
min,300.000000,1.000000,0.000000,10.000000,1.000000,1250.000000
25%,1110.000000,2.000000,1.000000,49.000000,2.000000,4244.864208
50%,1286.000000,2.000000,2.000000,67.000000,2.000000,5175.519668
75%,1650.000000,3.000000,2.000000,100.000000,3.000000,6428.571429
max,30400.000000,16.000000,3.000000,2200.000000,16.000000,24509.803922

In [33]:
def bhk_outliners_remove(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqt),
                'std': np.std(bhk_df.price_per_sqt),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.price_per_sqt < stats['mean']].index.values
                )
    return df.drop(exclude_indices, axis='index')

In [35]:
data = bhk_outliners_remove(data)

In [36]:
data.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,price_per_sqt
0,Super built-up Area,20-May,1st Block Jayanagar,4 BHK,NaN,2850.0,4.0,1.0,428.0,4,15017.543860
1,Super built-up Area,18-Jun,1st Block Jayanagar,3 BHK,NaN,1630.0,3.0,2.0,194.0,3,11901.840491
2,Super built-up Area,Ready To Move,1st Block Jayanagar,3 BHK,NaN,1875.0,2.0,3.0,235.0,3,12533.333333
3,Built-up Area,15-Dec,1st Block Jayanagar,3 BHK,Bhsic C,1200.0,2.0,0.0,130.0,3,10833.333333
4,Super built-up Area,18-Jun,1st Block Jayanagar,2 BHK,NaN,1235.0,2.0,2.0,148.0,2,11983.805668

In [37]:
data.drop(columns=['size','price_per_sqt'],inplace=True)

In [38]:
data

,area_type,availability,location,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,20-May,1st Block Jayanagar,NaN,2850.0,4.0,1.0,428.0,4
1,Super built-up Area,18-Jun,1st Block Jayanagar,NaN,1630.0,3.0,2.0,194.0,3
2,Super built-up Area,Ready To Move,1st Block Jayanagar,NaN,1875.0,2.0,3.0,235.0,3
3,Built-up Area,15-Dec,1st Block Jayanagar,Bhsic C,1200.0,2.0,0.0,130.0,3
4,Super built-up Area,18-Jun,1st Block Jayanagar,NaN,1235.0,2.0,2.0,148.0,2
...,...,...,...,...,...,...,...,...,...
10291,Carpet Area,19-Jan,other,NaN,1200.0,2.0,3.0,70.0,2
10292,Super built-up Area,Ready To Move,other,NaN,1800.0,1.0,1.0,200.0,1
10295,Super built-up Area,Ready To Move,other,OlarkLa,1353.0,2.0,2.0,110.0,2
10296,Plot Area,18-Jan,other,NaN,812.0,1.0,0.0,26.0,1
10299,Super built-up Area,Ready To Move,other,NaN,3600.0,5.0,NaN,400.0,4

In [39]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [40]:
data

                  location  total_sqft  bath  price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.0    4
1      1st Block Jayanagar      1630.0   3.0  194.0    3
2      1st Block Jayanagar      1875.0   2.0  235.0    3
3      1st Block Jayanagar      1200.0   2.0  130.0    3
4      1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
10291                other      1200.0   2.0   70.0    2
10292                other      1800.0   1.0  200.0    1
10295                other      1353.0   2.0  110.0    2
10296                other       812.0   1.0   26.0    1
10299                other      3600.0   5.0  400.0    4

[6798 rows x 5 columns]

In [41]:
data.to_csv("Cleaned_data.csv")

In [42]:
X = data.drop(columns=['price'])
y = data['price']

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

In [49]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')

In [55]:
lr = make_pipeline(
    StandardScaler(),
    LinearRegression()
)

In [56]:
pipe = make_pipeline(column_trans,lr)

In [57]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('pipeline',
                 Pipeline(steps=[('standardscaler', StandardScaler()),
                                 ('linearregression', LinearRegression())]))])

In [58]:
y_pred_lr = pipe.predict(X_test)

In [60]:
r2_score(y_test,y_pred_lr)

0.868688640454129

In [63]:
import pickle

In [64]:
pickle.dump(pipe,open('LinearRegression.pkl','wb'))